name: quiz_whiz
description: "A new Flutter project for a quiz application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^4.0.4
  provider: 6.1.2
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.png
    - assets/images/logo.png
    - assets/images/html.png
    - assets/images/css.png
    - assets/images/flutter.png
    - assets/images/cpp.png
    - assets/images/java.png
    - assets/images/php.png
    - assets/images/python.png
    - assets/images/javascript.png


